# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add',
            field=models.CharField(default='', max_length=100),
        ),
    ]
